export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_TRANSACTION_ERROR = 'ADD_TRANSACTION_ERROR';
